import { ROLES } from './roles';
import { ROUTES } from './routes';

export const ROUTE_PERMISSIONS = {
  [ROUTES.DASHBOARD]: [ROLES.ADMIN, ROLES.OPERACIONES, ROLES.CONSULTA],
  [ROUTES.CLIENTES]: [ROLES.ADMIN, ROLES.OPERACIONES, ROLES.CONSULTA],
  [ROUTES.CLIENTE_NUEVO]: [ROLES.ADMIN, ROLES.OPERACIONES],
  [ROUTES.CLIENTE_DETALLE]: [ROLES.ADMIN, ROLES.OPERACIONES, ROLES.CONSULTA],
  [ROUTES.ENVIOS]: [ROLES.ADMIN, ROLES.OPERACIONES, ROLES.CONSULTA],
  [ROUTES.ENVIO_NUEVO]: [ROLES.ADMIN, ROLES.OPERACIONES],
  [ROUTES.ENVIO_DETALLE]: [ROLES.ADMIN, ROLES.OPERACIONES, ROLES.CONSULTA],
  [ROUTES.ENVIO_TRAZABILIDAD]: [ROLES.ADMIN, ROLES.OPERACIONES, ROLES.CONSULTA],
  [ROUTES.HISTORIAL]: [ROLES.ADMIN, ROLES.OPERACIONES, ROLES.CONSULTA],
  [ROUTES.TRAZABILIDAD]: [ROLES.ADMIN, ROLES.OPERACIONES, ROLES.CONSULTA],
  [ROUTES.GEOLOCALIZACION]: [ROLES.ADMIN, ROLES.OPERACIONES, ROLES.CONSULTA],
  [ROUTES.GEOLOCALIZACION_DETALLE]: [ROLES.ADMIN, ROLES.OPERACIONES, ROLES.CONSULTA],
  [ROUTES.REPORTES]: [ROLES.ADMIN, ROLES.OPERACIONES, ROLES.CONSULTA],
  [ROUTES.USUARIOS]: [ROLES.ADMIN],
  [ROUTES.AUDITORIA]: [ROLES.ADMIN],
  [ROUTES.RESPALDO]: [ROLES.ADMIN],
  [ROUTES.PERFIL]: [ROLES.ADMIN, ROLES.OPERACIONES, ROLES.CONSULTA],
};

export const canMutate = (role) => role === ROLES.ADMIN || role === ROLES.OPERACIONES;

export const isAdmin = (role) => role === ROLES.ADMIN;
